name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_CONFIGURATION: Release

    steps:
    # 1) Checkout your code
    - uses: actions/checkout@v3

    # 2) Setup .NET 6 SDK
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    # 3) Restore, build, test
    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

    - name: Run unit tests
      run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }} --no-build

    # 4) SonarCloud analysis (optional)
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=expo-org
          -Dsonar.projectKey=expo-project
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    # 5) Deploy .NET backend to Azure Web App
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: expo-backend-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/YourProjectPath/bin/${{ env.BUILD_CONFIGURATION }}/net6.0/publish

    # 6) Deploy front end to Static Web App
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        api_location: ""
        output_location: "dist"

