name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        dotnet-version: [6.0.x]

    steps:
      - uses: actions/checkout@v3

      - name: SonarCloud Scan (pre-build)
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=expo-project
            -Dsonar.organization=expo-org
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore & Build Backend
        run: dotnet build ./backend --configuration Release

      - name: SonarCloud Scan (post-build)
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=expo-project
            -Dsonar.organization=expo-org
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Test Backend
        run: dotnet test ./backend --configuration Release

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm start

      - name: Deploy Frontend
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GH_TOKEN }}
          action: upload
          app_location: "frontend"
          output_location: "frontend/dist"

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: expo-backend-app
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/bin/Release/net6.0/publish

